---

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Create configuration directories
  ansible.builtin.file:
    path: /etc/nginx/{{ item }}
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - ssl
    - conf.d

- name: Configure nginx for opencast
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /etc/nginx/{{ item }}
    mode: '0644'
    owner: root
    group: root
  notify: Reload nginx
  loop:
    - nginx.conf
    - conf.d/tls.conf
    - conf.d/http.conf

- name: Generate diffie-hellman parameters
  community.crypto.openssl_dhparam:
    path: /etc/nginx/ssl/dhparam.pem
    size: 2048
    mode: '0640'
    owner: root
    group: root
  notify: Reload nginx

- name: Create extra configuration file
  ansible.builtin.copy:
    src: extra.conf
    dest: /etc/nginx/conf.d/extra.conf
    owner: root
    group: root
    mode: '0644'
    force: false
  notify: Reload nginx

- name: Install dummy tls certificate
  ansible.builtin.copy:
    src: dummy-tls-{{ item }}.pem
    dest: /etc/nginx/ssl/{{ inventory_hostname }}.{{ item }}
    owner: root
    group: root
    mode: '0400'
    force: false
  notify: Reload nginx
  loop:
    - key
    - crt

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
