---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test that nginx redirects to https
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}/
        follow_redirects: none
        status_code: 301

    - name: Test that nginx acts as proxy on https
      ansible.builtin.uri:
        url: https://{{ inventory_hostname }}/
        validate_certs: false
        follow_redirects: none
        status_code: 502

    - name: Add extra configuration
      ansible.builtin.copy:
        content: 'location /test { return 204; }'
        dest: /etc/nginx/conf.d/extra.conf
        mode: '0644'

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Test extra configuration
      ansible.builtin.uri:
        url: https://{{ inventory_hostname }}/test
        validate_certs: false
        follow_redirects: none
        status_code: 204
